spring:
  application:
    name: booking-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: booking_group
      auto-offset-reset: earliest
  datasource:
    url: jdbc:mysql://localhost:3306/Uber_Db_Local
    username: root
    password: Mac@local
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

server:
  port: 7477

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.org.example.uberprojectbookingservice: DEBUG


